sudo: false

language: elixir

elixir:
        - 1.3.4
        - 1.4.5
        - 1.5.3
        - 1.6.6
        - 1.7.3

otp_release:
        - 19.1
        - 20.3
        - 21.1

script:
        - "MIX_ENV=test mix do deps.get, deps.compile, coveralls.travis"
